cloud:
  aws:
    s3:
      bucket: e-room
      dev-bucket: e-room-dev
      folder:
        reviewImages: review-images
        profileImages: profile-images
        thumbnailImages: thumbnail-images
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    cloudFront:
      distributionDomain: https://d2ykyi5jl9muoc.cloudfront.net
      dev-distributionDomain: cdn.e-room.dev