cloud:
  aws:
    s3:
      bucket: e-room
      folder:
        reviewImages: review-images
        profileImages: profile-images
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}